on:
  push:
    branches:
      - main

permissions:
  contents: write

name: ðŸš€ Deploy da aplicaÃ§Ã£o na VPS

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest

    steps:
      - name: ðŸšš Listando cÃ³digos
        uses: actions/checkout@v3
      
      - name: ðŸ“‚ Sincronizar Arquivos via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTPSERVER }}
          username: ${{ secrets.FTPLOGIN }}
          password: ${{ secrets.FTPPASS }}

      - name: ðŸ“¢ Enviar notificaÃ§Ã£o ao Telegram
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="âœ… Deploy da aplicaÃ§Ã£o Streamlit controleGastos, finalizado com sucesso no servidor da VPS!"
